name: Build Android APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install dependencies
        run: npm install

      - name: Build web app for mobile
        run: npm run build:mobile

      - name: Add Android platform
        run: npx cap add android

      - name: Copy web assets
        run: npx cap copy android

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build debug APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: attendance-tracker-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: AttendanceTracker v${{ github.run_number }}
          body: |
            📱 **AttendanceTracker APK Build**

            **Features:**
            - ✅ Track attendance with Present/Absent buttons
            - ✅ Custom subject creation
            - ✅ Timetable management
            - ✅ Attendance undo functionality
            - ✅ Subject-wise statistics
            - ✅ Offline data storage

            **Installation:**
            1. Download the APK file below
            2. Enable "Unknown Sources" in Android settings
            3. Install the APK

            Auto-built from commit: ${{ github.sha }}
          files: android/app/build/outputs/apk/debug/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
